import { HomeCookingRecipe } from './types';
export type { HomeCookingRecipe };

export const POPULAR_HOME_COOKING_RECIPES: HomeCookingRecipe[] = [
  {
    id: 'recipe-turkey-rice',
    title: 'Mediterranean Lean Turkey & Long-Grain Rice',
    greekTitle: 'Μεσογειακή Άπαχη Γαλοπούλα με Ρύζι & Κολοκυθάκια',
    subtitle: 'Daily gentle maintenance formula for dogs with sensitive digestion or poultry tolerance',
    targetProfile: 'Daily Maintenance & Sensitive Stomach',
    dogSizeSuitability: 'All Breeds (5kg – 45kg)',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    dailyPortionPer10KgDog: 'approx. 380g – 420g split into two meals (approx. 40g per kg of ideal body weight)',
    ingredients: [
      { name: 'Ground Lean Turkey Breast (93/7)', quantityGrams: 500, purpose: 'Easily digestible lean animal protein' },
      { name: 'Parboiled White or Jasmine Rice (cooked weight ~600g)', quantityGrams: 200, purpose: 'Gentle complex carbohydrate source with near-zero irritation' },
      { name: 'Zucchini (steamed & diced)', quantityGrams: 150, purpose: 'Hydrating soluble fiber & potassium' },
      { name: 'Carrots (finely shredded & steamed)', quantityGrams: 100, purpose: 'Beta-carotene, vitamin A & ocular health' },
      { name: 'Fresh Spinach leaves (steamed)', quantityGrams: 50, purpose: 'Iron, lutein & magnesium' },
      { name: 'Extra Virgin Greek Olive Oil', quantityGrams: 15, purpose: 'Oleic acid, vitamin E & palatable healthy fats' },
    ],
    stepByStepInstructions: [
      'In a medium pot, boil the parboiled rice in unseasoned water until tender and soft (dogs digest softer rice far better than al dente). Drain excess water.',
      'Lightly steam or simmer ground turkey in a non-stick pan with 1/2 cup of water without any onions, garlic, or salt until fully cooked and no pink remains.',
      'Steam diced zucchini and shredded carrots until fork-tender (approx. 8 minutes). Fold in spinach leaves in the last 2 minutes to wilt lightly.',
      'Combine the cooked turkey, rice, and steamed vegetables in a large mixing bowl. Allow to cool completely to room temperature.',
      'Drizzle with Greek extra virgin olive oil and thoroughly stir in the calcium/micronutrient balancer before serving.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'All meat is high in phosphorus and low in calcium (1:15 ratio). Balancing with calcium is mandatory to prevent metabolic bone deficiency.',
      recommendedSupplement: 'Calcium Carbonate or clean sterilized eggshell powder: 1/2 level teaspoon (approx. 2.5g elemental calcium) per 500g cooked meat.',
      omega3Source: '1 teaspoon wild Icelandic salmon oil or sardine oil (adds EPA/DHA essential for cell membrane integrity).',
      essentialVitamins: 'Standard veterinary canine multivitamin powder (containing Vitamin D3, E, Zinc, and Taurine).',
    },
    macronutrientsPer100g: {
      proteinPercent: 11.2,
      fatPercent: 4.8,
      fiberPercent: 1.4,
      moisturePercent: 71.5,
      kcalPer100g: 124,
    },
    veterinaryNotes: 'Turkey is a hypoallergenic, low-fat alternative to chicken. Excellent starter recipe for dogs transitioning from commercial kibble to fresh food.',
    storageInstructions: 'Keep refrigerated in an airtight glass container for up to 4 days. Can be portioned into silicone bags and frozen for up to 3 months.',
  },
  {
    id: 'recipe-beef-pumpkin',
    title: 'Greek Beef, Pumpkin Puree & Brown Rice',
    greekTitle: 'Μοσχάρι με Κολοκύθα, Καστανό Ρύζι & Φασολάκια',
    subtitle: 'High-energy recipe with soluble pectin fiber for firm, consistent stools and athletic dogs',
    targetProfile: 'Active Dogs, Muscle Conditioning & Stool Regularity',
    dogSizeSuitability: 'Medium to Large Breeds (12kg – 55kg)',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    dailyPortionPer10KgDog: 'approx. 350g – 380g split into two meals',
    ingredients: [
      { name: 'Lean Ground Beef (85/15)', quantityGrams: 550, purpose: 'Rich bioavailable zinc, iron, B12 & amino acids' },
      { name: '100% Pure Pumpkin Puree (Cucurbita pepo)', quantityGrams: 150, purpose: 'Pectin fiber that regulates intestinal transit and firms loose stools' },
      { name: 'Brown Rice (measured raw, cooked tender)', quantityGrams: 180, purpose: 'Slow-burn glycemic energy with manganese & magnesium' },
      { name: 'Green Beans (fresh or frozen, steamed & chopped)', quantityGrams: 120, purpose: 'Low-calorie bulk fiber, vitamin C and folic acid' },
      { name: 'Wild Blueberries (fresh or thawed)', quantityGrams: 50, purpose: 'High polyphenol anthocyanins for cellular antioxidant defense' },
    ],
    stepByStepInstructions: [
      'Rinse brown rice thoroughly and boil in water (1:2.5 ratio) for 30 minutes until grains are completely soft and swollen.',
      'Brown the ground beef in a skillet over medium heat without adding oils or seasonings. Drain excess liquid fat if your dog requires a leaner profile.',
      'Steam the green beans until soft, then roughly chop into small bite-sized pieces so they do not pass through undigested.',
      'Mix the warm cooked beef, drained brown rice, steamed green beans, pure pumpkin puree, and blueberries together.',
      'Cool to below 35°C (lukewarm or room temperature) before mixing in the calcium supplement and serving.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Beef is naturally high in phosphorus; strict calcium supplementation is required.',
      recommendedSupplement: 'Bone meal powder or calcium carbonate: 3g per 500g meat.',
      omega3Source: '1 teaspoon fish oil (herring or sardine oil).',
      essentialVitamins: 'Taurine (250mg) and Canine Vitamin E (50 IU) to combat lipid oxidation from red meat.',
    },
    macronutrientsPer100g: {
      proteinPercent: 12.8,
      fatPercent: 6.2,
      fiberPercent: 1.8,
      moisturePercent: 69.0,
      kcalPer100g: 142,
    },
    veterinaryNotes: 'Pumpkin is the #1 veterinarian-recommended gastrointestinal stabilizer in fresh canine diets.',
    storageInstructions: 'Refrigerate up to 3 days, or freeze in daily portion tubs for up to 90 days.',
  },
  {
    id: 'recipe-white-fish-sweet-potato',
    title: 'Aegean White Fish (Hake/Cod) & Sweet Potato',
    greekTitle: 'Ψάρι Αιγαίου (Μπακαλιάρος) με Γλυκοπατάτα & Μπρόκολο',
    subtitle: 'Ultra-low allergen, novel fish diet designed for dogs with severe food allergies and ear/skin inflammation',
    targetProfile: 'Severe Atopic Allergies, Elimination Diet & Pancreatitis Prevention',
    dogSizeSuitability: 'All Breeds, Especially Small & Allergy-Prone Breeds',
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    dailyPortionPer10KgDog: 'approx. 400g – 440g split into two meals',
    ingredients: [
      { name: 'Fresh or Frozen Wild White Fish (Hake, Cod, or Pollock, boneless)', quantityGrams: 600, purpose: 'Ultra-pure, hypoallergenic single-protein with negligible saturated fat' },
      { name: 'Sweet Potatoes (peeled & thoroughly boiled/mashed)', quantityGrams: 300, purpose: 'Soluble prebiotic starch, vitamins A & B6, gentler than grains' },
      { name: 'Broccoli florets (steamed & pureed)', quantityGrams: 100, purpose: 'Sulforaphane antioxidant & fiber' },
      { name: 'Organic Cold-Pressed Flaxseed Oil or Olive Oil', quantityGrams: 15, purpose: 'Essential linoleic & alpha-linolenic fatty acids' },
    ],
    stepByStepInstructions: [
      'Carefully inspect white fish fillets to guarantee 100% absence of bones. Gently poach fish fillets in simmering water for 7–9 minutes until flaky.',
      'Peel sweet potatoes, dice into small cubes, and boil until very soft (approx. 18 minutes). Mash with a fork.',
      'Steam broccoli florets until bright green and tender, then puree or finely mince.',
      'Flake the cooked fish and combine with mashed sweet potatoes, broccoli, and cold-pressed oil in a mixing bowl.',
      'Allow the mixture to cool to room temperature. Add calcium carbonate and canine essential minerals.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'White fish contains lower phosphorus than red meat, but calcium is still required to hit the 1.2:1 Ca:P ratio.',
      recommendedSupplement: 'Canine Calcium Citrate or Eggshell Powder: 2.2g per 500g fish.',
      omega3Source: 'Natural fish contains EPA/DHA; add 1/2 tsp krill oil for enhanced bio-availability.',
      essentialVitamins: 'Iodine & Zinc methionine (vital for white fish single-source diets).',
    },
    macronutrientsPer100g: {
      proteinPercent: 10.5,
      fatPercent: 2.9,
      fiberPercent: 1.6,
      moisturePercent: 76.2,
      kcalPer100g: 105,
    },
    veterinaryNotes: 'Ideal prescription replacement for commercial dermatological hydrolyzed diets. Exceptionally well-tolerated by French Bulldogs, Malteses, and Westies.',
    storageInstructions: 'Fish degrades faster than poultry: keep refrigerated for maximum 48–72 hours, freeze remainder immediately.',
  },
  {
    id: 'recipe-senior-chicken-carrot',
    title: 'Chicken Breast & Carrot Gentle Senior Stew',
    greekTitle: 'Σιγοβρασμένο Κοτόπουλο με Καρότο & Βρώμη για Ηλικιωμένους',
    subtitle: 'Low-fat, highly digestible warm stew with beta-glucan oats to support joint mobility and cardiac health in aging dogs',
    targetProfile: 'Senior Dogs (7+ Years), Weight Management & Renal Ease',
    dogSizeSuitability: 'Senior Dogs of Any Breed',
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    dailyPortionPer10KgDog: 'approx. 360g – 400g split into two meals',
    ingredients: [
      { name: 'Skinless Chicken Breast Fillet', quantityGrams: 500, purpose: 'Ultra-pure lean protein with minimal purines and low phosphorus' },
      { name: 'Rolled Oats (cooked in water to a porridge)', quantityGrams: 160, purpose: 'Heart-healthy beta-glucans, slow carbohydrates, and cholesterol control' },
      { name: 'Carrots & Yellow Pumpkin (diced & stewed)', quantityGrams: 180, purpose: 'Soft fiber, lutein and easy gastrointestinal passage' },
      { name: 'Unsalted Bone Broth (homemade chicken/beef, no onions)', quantityGrams: 200, purpose: 'Natural glucosamine, chondroitin & collagen hydration' },
      { name: 'Ground Turmeric + pinch of black pepper', quantityGrams: 2, purpose: 'Natural curcumin anti-inflammatory for arthritic joints' },
    ],
    stepByStepInstructions: [
      'Dice chicken breast into small cubes. In a stockpot, simmer the chicken in 3 cups of water or unsalted homemade bone broth for 15 minutes.',
      'Add the diced carrots and pumpkin into the same broth; simmer until vegetables are meltingly soft.',
      'Stir in rolled oats and reduce heat to low, cooking for 6–8 minutes until a thick, comforting stew forms.',
      'Sprinkle in ground turmeric and stir thoroughly.',
      'Cool thoroughly. The rich natural broth makes this irresistibly fragrant for senior dogs with diminished olfactory senses.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Senior dogs require tightly controlled Ca:P to safeguard aging kidneys.',
      recommendedSupplement: 'Medical grade Calcium Carbonate: 2.5g per 500g meat.',
      omega3Source: '1.5 teaspoons salmon oil high in DHA to support cognitive function (canine cognitive dysfunction syndrome).',
      essentialVitamins: 'Joint complex (Glucosamine 500mg, Chondroitin 400mg, MSM 250mg) mixed into serving.',
    },
    macronutrientsPer100g: {
      proteinPercent: 11.5,
      fatPercent: 3.2,
      fiberPercent: 1.5,
      moisturePercent: 74.5,
      kcalPer100g: 112,
    },
    veterinaryNotes: 'Oats provide gentle gut motility for older dogs prone to constipation. Bone broth stimulates appetite and lubricates stiff joints.',
    storageInstructions: 'Refrigerate in sealed containers up to 4 days, or freeze in daily meal containers for up to 2 months.',
  },
  {
    id: 'recipe-lamb-lentils',
    title: 'Cretan Lamb & Green Lentil Monoprotein Stew',
    greekTitle: 'Κρητικό Αρνάκι με Ψιλές Φακές, Σπανάκι & Κολοκύθα',
    subtitle: 'Rich in natural L-carnitine, zinc, and iron for working dogs, shepherds, and breeds needing robust muscle tone',
    targetProfile: 'High-Energy Working Dogs, Shepherds & Poultry-Allergic Pets',
    dogSizeSuitability: 'Active Medium to Large Breeds (15kg – 60kg)',
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    dailyPortionPer10KgDog: 'approx. 340g – 370g split into two meals',
    ingredients: [
      { name: 'Lean Lamb Muscle Meat (trimmed of excess fat)', quantityGrams: 550, purpose: 'Hypoallergenic red meat rich in carnitine and muscle-building amino acids' },
      { name: 'Greek Green Lentils (soaked overnight & boiled soft)', quantityGrams: 140, purpose: 'Plant protein, prebiotic oligosaccharides, folate and iron' },
      { name: 'Butternut Squash or Pumpkin (boiled & mashed)', quantityGrams: 150, purpose: 'Vitamin A, potassium, and digestive buffer against gas' },
      { name: 'Chopped Greek Celery stalks (steamed)', quantityGrams: 50, purpose: 'Phytonutrients, natural sodium, and crisp texture' },
      { name: 'Greek Olive Oil', quantityGrams: 12, purpose: 'Monounsaturated oleic fats & antioxidant protection' },
    ],
    stepByStepInstructions: [
      'Soak lentils in fresh water for at least 6 hours, then rinse and boil in fresh unseasoned water for 35 minutes until completely tender and easily mashed.',
      'Cut lamb meat into bite-sized cubes. Braise gently in a pan with 1 cup of water over medium-low heat until tender and fully cooked.',
      'Steam butternut squash and celery until soft.',
      'Combine the cooked lamb, thoroughly cooked lentils, mashed squash, and celery in a large bowl.',
      'Add Greek olive oil, let cool, and fold in canine calcium balancer.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Lamb muscle is moderately high in phosphorus (approx 200mg/100g).',
      recommendedSupplement: 'Canine Calcium Carbonate: 2.8g per 500g lamb.',
      omega3Source: '1 teaspoon concentrated wild marine fish oil.',
      essentialVitamins: 'Taurine (250mg) to support cardiovascular health.',
    },
    macronutrientsPer100g: {
      proteinPercent: 13.5,
      fatPercent: 6.8,
      fiberPercent: 2.2,
      moisturePercent: 68.5,
      kcalPer100g: 150,
    },
    veterinaryNotes: 'Legumes must always be thoroughly soaked and boiled until very soft to neutralize lectins and ensure canine digestion.',
    storageInstructions: 'Refrigerate up to 4 days, or freeze in portions up to 3 months.',
  },
  {
    id: 'recipe-pork-quinoa',
    title: 'Lean Pork Loin & Quinoa Anti-Allergenic Bowl',
    greekTitle: 'Άπαχο Χοιρινό Φιλέτο με Κινόα & Πράσινα Μπιζέλια',
    subtitle: 'Novel clean protein paired with gluten-free ancient pseudo-grain for dogs intolerant to beef and chicken',
    targetProfile: 'Food Sensitivity, Elimination Diets & Grain-Free Tolerance',
    dogSizeSuitability: 'All Breeds (8kg – 40kg)',
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    dailyPortionPer10KgDog: 'approx. 370g – 400g split into two meals',
    ingredients: [
      { name: 'Lean Pork Loin or Tenderloin (fat trimmed)', quantityGrams: 520, purpose: 'High thiamine (B1), selenium, and novel clean protein' },
      { name: 'White Quinoa (thoroughly rinsed & boiled)', quantityGrams: 160, purpose: 'Complete amino acid profile ancient grain, gluten-free and low-glycemic' },
      { name: 'Green Peas (steamed)', quantityGrams: 100, purpose: 'Vegetable protein, lutein, zeaxanthin & dietary fiber' },
      { name: 'Red Apples (cored, seeded & diced)', quantityGrams: 70, purpose: 'Quercetin antioxidant, pectin fiber (NEVER include apple seeds)' },
      { name: 'Virgin Coconut Oil or Hemp Seed Oil', quantityGrams: 10, purpose: 'Medium-chain triglycerides (MCTs) & omega-6/3 balance' },
    ],
    stepByStepInstructions: [
      'Rinse quinoa thoroughly in a fine-mesh sieve under cold running water to strip away natural saponins. Simmer in water (1:2 ratio) for 15 minutes.',
      'Cut lean pork loin into bite-sized cubes and pan-cook in water until internal temperature reaches 74°C (completely cooked).',
      'Steam green peas and diced peeled apple until tender.',
      'Mix the cooked pork, fluffy quinoa, steamed peas, and apples together.',
      'Allow to cool completely to room temperature, stir in coconut or hemp oil and calcium supplement.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Pork requires standard Ca:P balancing.',
      recommendedSupplement: 'Calcium Carbonate: 2.5g per 500g pork meat.',
      omega3Source: '1 teaspoon sardine/anchovy oil.',
      essentialVitamins: 'Standard canine mineral premix.',
    },
    macronutrientsPer100g: {
      proteinPercent: 12.0,
      fatPercent: 4.5,
      fiberPercent: 1.7,
      moisturePercent: 71.0,
      kcalPer100g: 130,
    },
    veterinaryNotes: 'Pork tenderloin is one of the leanest, most digestible meats available and is rarely cross-reactive with poultry or ruminant allergies.',
    storageInstructions: 'Refrigerate up to 4 days; freeze up to 90 days.',
  },
  {
    id: 'recipe-salmon-spinach',
    title: 'Aegean Salmon, Spinach & Olive Oil Coat Glow',
    greekTitle: 'Σολομός με Σπανάκι, Γλυκοπατάτα & Ελαιόλαδο για Λαμπερό Τρίχωμα',
    subtitle: 'Packed with bioactive EPA & DHA fatty acids to combat dry itchy skin, shedding, and dull coats',
    targetProfile: 'Dermatological Recovery, Dull Coat, Shedding & Dry Itchy Skin',
    dogSizeSuitability: 'All Breeds, Especially Double-Coated & Long-Haired Breeds',
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    dailyPortionPer10KgDog: 'approx. 360g – 390g split into two meals',
    ingredients: [
      { name: 'Fresh Salmon Fillet (skin-on, boneless)', quantityGrams: 500, purpose: 'Primary marine protein loaded with anti-inflammatory EPA/DHA and astaxanthin' },
      { name: 'Sweet Potato (steamed & mashed)', quantityGrams: 280, purpose: 'Complex carbs and high vitamin A for skin epithelial regeneration' },
      { name: 'Baby Spinach (lightly wilted)', quantityGrams: 80, purpose: 'Chlorophyll, iron, vitamin K, and folic acid' },
      { name: 'Zucchini (grated & steamed)', quantityGrams: 100, purpose: 'Moisture balance & gentle bulk' },
      { name: 'Greek Extra Virgin Olive Oil', quantityGrams: 10, purpose: 'Skin lipid barrier support and vitamin E' },
    ],
    stepByStepInstructions: [
      'Ensure the salmon fillet is 100% debone-checked. Steam or bake the salmon fillet at 180°C for 15 minutes until it flakes easily.',
      'Steam sweet potatoes until completely soft, then mash smoothly with a fork.',
      'Lightly steam grated zucchini and baby spinach for 3–4 minutes until tender.',
      'Flake salmon (including the nutrient-dense cooked skin if tolerated) into bite-sized pieces and fold together with the mashed sweet potato and vegetables.',
      'Let cool thoroughly to room temperature before blending in calcium balancer.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Salmon is high in phosphorus and natural healthy fats.',
      recommendedSupplement: 'Calcium carbonate: 2.3g per 500g salmon.',
      omega3Source: 'Natural salmon provides abundant EPA/DHA; no extra fish oil needed.',
      essentialVitamins: 'Canine Vitamin E (100 IU) to protect unsaturated fatty acids from oxidative rancidity in vivo.',
    },
    macronutrientsPer100g: {
      proteinPercent: 11.8,
      fatPercent: 7.2,
      fiberPercent: 1.5,
      moisturePercent: 70.0,
      kcalPer100g: 148,
    },
    veterinaryNotes: 'Astaxanthin in wild/farmed salmon is one of nature’s most potent free radical scavengers for canine cellular defense.',
    storageInstructions: 'Refrigerate up to 3 days maximum, or freeze portioned containers up to 2 months.',
  },
  {
    id: 'recipe-recovery-cottage-egg',
    title: 'Cottage Cheese, Soft Egg & Jasmine Rice Upset-Stomach Reset',
    greekTitle: 'Ανάλαφρο Μείγμα: Ανθότυρο/Cottage, Αυγό & Λευκό Ρύζι Ανάρρωσης',
    subtitle: 'Classic veterinary bland recovery diet for acute gastroenteritis, post-surgery convalescence, or diarrhea recovery',
    targetProfile: 'Acute Gastritis Recovery, Post-Diarrhea Reset & Convalescence',
    dogSizeSuitability: 'All Breeds (Short-Term Use 3 to 7 Days)',
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    dailyPortionPer10KgDog: 'approx. 320g – 360g fed in 3 to 4 small frequent portions throughout the day',
    ingredients: [
      { name: 'Low-Fat Greek Cottage Cheese (or fresh unsalted Myzithra/Anthotyro)', quantityGrams: 250, purpose: 'Ultra-gentle casein protein with live probiotic cultures to reseed gut flora' },
      { name: 'Free-Range Eggs (softly scrambled in water, no butter/oil)', quantityGrams: 150, purpose: 'The highest biological value protein in nature (BV = 100), full amino acid spectrum' },
      { name: 'Overcooked White Jasmine or Basmati Rice (measured cooked)', quantityGrams: 400, purpose: 'Binds excess intestinal fluid, provides instant glycogen without fermentative gas' },
      { name: 'Pure Boiled Carrot Puree', quantityGrams: 100, purpose: 'Oligosaccharides that block pathogenic bacteria from adhering to the intestinal wall' },
    ],
    stepByStepInstructions: [
      'Boil white rice with excess water for 25 minutes so it is noticeably softer and starchier than human rice.',
      'Boil carrots until very soft and puree with a splash of the cooking water (Moro carrot soup principle).',
      'Whisk eggs with 2 tablespoons of water and cook gently in a non-stick pan over low heat without adding any oil, butter, or salt.',
      'Combine warm soft rice, pureed carrots, softly scrambled egg, and low-fat cottage cheese/anthotyro.',
      'Serve at lukewarm temperature in 3–4 mini-meals throughout the day to prevent stomach distention.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'This is an acute recovery therapeutic diet meant for 3 to 7 days. Long-term use requires full Ca:P balancer, but short term is safe.',
      recommendedSupplement: 'Optional: 1 pinch of powdered eggshell if feeding beyond 5 consecutive days.',
      omega3Source: 'Withhold heavy oils during acute diarrhea until stool firms.',
      essentialVitamins: 'Canine veterinary probiotic powder (Enterococcus faecium SF68) sprinkled on top right before feeding.',
    },
    macronutrientsPer100g: {
      proteinPercent: 8.5,
      fatPercent: 3.5,
      fiberPercent: 0.8,
      moisturePercent: 78.0,
      kcalPer100g: 98,
    },
    veterinaryNotes: 'The legendary "Moro Carrot Soup" principle: boiled carrot oligosaccharides mimic intestinal receptors, preventing bacteria like E. coli from latching on.',
    storageInstructions: 'Prepare fresh every 48 hours. Refrigerate in glass containers.',
  },
  {
    id: 'recipe-novel-rabbit-zucchini',
    title: 'Novel Protein Farm Rabbit & Zucchini Medley',
    greekTitle: 'Εκλεκτό Κουνέλι με Κολοκυθάκια & Γλυκοπατάτα',
    subtitle: 'Hypoallergenic single-protein meal for dogs that have developed allergies to chicken, beef, lamb, and pork',
    targetProfile: 'Chronic Ear Infections, Inflammatory Bowel Disease (IBD) & Elimination Protocol',
    dogSizeSuitability: 'All Breeds (5kg – 40kg)',
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    dailyPortionPer10KgDog: 'approx. 380g – 420g split into two meals',
    ingredients: [
      { name: 'Deboned Farm Rabbit Meat', quantityGrams: 550, purpose: 'Exceptional novel meat with highest protein-to-fat ratio and near-zero allergic memory' },
      { name: 'Sweet Potato (boiled & mashed)', quantityGrams: 250, purpose: 'Hypoallergenic slow-digesting carbohydrate and dietary potassium' },
      { name: 'Zucchini (steamed & cubed)', quantityGrams: 150, purpose: 'Low-glycemic soluble prebiotic fiber and hydration' },
      { name: 'Fresh Parsley (finely chopped)', quantityGrams: 15, purpose: 'Natural breath freshener, flavonoids, and kidney flushing support' },
      { name: 'Extra Virgin Olive Oil', quantityGrams: 12, purpose: 'Healthy fats & omega-9' },
    ],
    stepByStepInstructions: [
      'Carefully inspect and debone rabbit meat. Cut into small chunks and simmer in water for 20 minutes until cooked through.',
      'Boil sweet potato and steam zucchini until fork-tender.',
      'Mash sweet potatoes and fold in the cooked rabbit chunks, steamed zucchini, and fresh finely chopped parsley.',
      'Drizzle with extra virgin olive oil and allow to cool completely.',
      'Mix in the mandatory calcium balancer.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Rabbit is exceptionally lean, requiring precise calcium supplementation to maintain Ca:P balance.',
      recommendedSupplement: 'Canine Calcium Carbonate: 2.6g per 500g rabbit meat.',
      omega3Source: '1 teaspoon wild sardine or anchovy oil.',
      essentialVitamins: 'Canine B-complex and Taurine.',
    },
    macronutrientsPer100g: {
      proteinPercent: 13.0,
      fatPercent: 3.8,
      fiberPercent: 1.5,
      moisturePercent: 72.5,
      kcalPer100g: 122,
    },
    veterinaryNotes: 'Rabbit is recognized by veterinary dermatologists worldwide as the gold standard for canine elimination diet trials.',
    storageInstructions: 'Keep refrigerated up to 4 days; freeze portions up to 90 days.',
  },
  {
    id: 'recipe-organ-meat-vitality',
    title: 'Beef Liver, Heart & Sweet Potato Vitality Booster',
    greekTitle: 'Μοσχαρίσια Καρδιά, Συκώτι & Γλυκοπατάτα Ενέργειας',
    subtitle: 'High-density natural organ meat blend rich in CoQ10, iron, copper, and vitamin A for stamina and immune vitality',
    targetProfile: 'Athletic Dogs, Anemia Recovery, Stamina & Natural Nutrient Boost',
    dogSizeSuitability: 'Active Adult Dogs (Not for Puppies or Dogs with Copper Storage Disease)',
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    dailyPortionPer10KgDog: 'approx. 330g – 360g split into two meals, or used 2–3 times per week as a superfood topper',
    ingredients: [
      { name: 'Beef Heart (diced, fat trimmed)', quantityGrams: 350, purpose: 'Muscle organ meat packed with CoQ10, taurine, and high bioavailable protein' },
      { name: 'Beef Liver (diced)', quantityGrams: 100, purpose: 'Nature’s multivitamin: bioavailable Vitamin A, B12, iron, and copper (kept to ~10% total)' },
      { name: 'Lean Ground Beef (90/10)', quantityGrams: 150, purpose: 'Balancing muscle protein base' },
      { name: 'Sweet Potato (boiled & cubed)', quantityGrams: 220, purpose: 'Complex carbs and dietary fiber' },
      { name: 'Spinach & Carrots (steamed)', quantityGrams: 120, purpose: 'Antioxidants, lutein, and magnesium' },
      { name: 'Wild Blueberries', quantityGrams: 40, purpose: 'Antioxidant protection against cellular stress' },
    ],
    stepByStepInstructions: [
      'Trim any tough connective tissue from beef heart and dice into 1cm cubes. Dice beef liver into small pieces.',
      'Gently simmer diced heart, liver, and ground beef in water for 15 minutes until cooked through. Do not overcook liver to preserve heat-sensitive B vitamins.',
      'Steam sweet potato, carrots, and spinach until tender.',
      'Combine all meats, vegetables, and wild blueberries in a large bowl and mash lightly to blend flavors.',
      'Cool completely to room temperature before adding calcium balancer.',
    ],
    vitalNutritionalBalancer: {
      calciumPhosphorusRule: 'Heart and liver are very rich in phosphorus (over 300mg/100g). Exact calcium balancing is critical.',
      recommendedSupplement: 'Canine Calcium Carbonate: 3.2g per 500g organ/muscle blend.',
      omega3Source: '1 teaspoon wild salmon oil.',
      essentialVitamins: 'Natural organ meat provides almost all required vitamins; no synthetic vitamin A needed.',
    },
    macronutrientsPer100g: {
      proteinPercent: 14.2,
      fatPercent: 5.5,
      fiberPercent: 1.4,
      moisturePercent: 70.0,
      kcalPer100g: 145,
    },
    veterinaryNotes: 'Liver should never exceed 10% of a dog’s total diet to prevent hypervitaminosis A. Heart is muscular organ meat and safe in higher quantities.',
    storageInstructions: 'Refrigerate up to 3 days, or freeze in individual meal portions for up to 3 months.',
  },
];
